version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/app
    environment:
      API_SERVER_ADDR: ":8080"
    ports:
    - "8080:8080"